FROM node:20-alpine

WORKDIR /app

# Instalar dependencias del sistema necesarias para Prisma en Alpine
RUN apk add --no-cache openssl libc6-compat

# Habilitar pnpm
RUN corepack enable pnpm

# Copiar archivos de configuración del workspace y dependencias raíz
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

# Copiar los paquetes compartidos y apps
COPY packages/ ./packages/
COPY apps/ ./apps/

# Establecer el directorio de trabajo en el microservicio correspondiente (ej. api-gateway)
WORKDIR /app/apps/api-gateway

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]
